### ISSUE TITLE
API docs fo 0.3.3 and Orders

### ISSUE THREAD

**Issue by fominok** [David-OConnor/seed#113]
Hello, I've tried to put TodoMVC outside of examples into my project, but `Orders` are not found, also on 0.3.2 docs I cannot find them as well. 0.3.3 docs are not built due to some usual nightly tooling issues. Could you tell me, what Orders is and how to use TodoMVC outsise of seed repo?

**Comment by David-OConnor** [comment]
This is due to the repo and examples including breaking changes since v0.3.3. The v0.3.4 release is now live - the docs are now built correctly, and the examples match the release.

Orders is a new way of managing updates, recently written by @MartinKavik . Here's [an example](https://github.com/David-OConnor/seed/blob/master/examples/orders/src/lib.rs).

[Description](https://github.com/David-OConnor/seed/issues/106), at the bottom of this page.

See the [update section of this guide page](https://seed-rs.org/guide/2)

**Comment by fominok** [comment]
Thank you for clarifying!
