### ISSUE TITLE
A question regarding `sink` vs `update`.

### ISSUE THREAD

**Issue by AlterionX** [David-OConnor/seed#228]
I've personally been using the same function for my function and sink. Here's my initialization procedure:

```rust
#[wasm_bindgen(start)]
pub fn begin_app() {
    log("Beginning render.");

    let app = seed::App::build(init, update, view).sink(update);
    let body_tag = seed::body();
    let app = match body_tag.query_selector("main") {
        Ok(Some(main_tag)) => app.mount(main_tag),
        _ => app.mount(body_tag),
    };
    let app = app.routes(routes).finish();
    app.run();
}
```

Notice that `sink` takes in the same function as the `update` parameter in the `build` function.

Thus, I'm confused as to why sink is separated from everything else.

**Comment by MartinKavik** [comment]
`sink` should be used in larger apps - it helps you when you have more submodules, so it probably doesn't make sense in the given example. See https://github.com/David-OConnor/seed/pull/189 - **7. change** for more info.

**Comment by MartinKavik** [comment]
OT: I think you can make that example a little bit more readable:
```rust
#[wasm_bindgen(start)]
pub fn begin_app() {
    log("Beginning render.");

    let mount_point = match seed::body().query_selector("main") {
        Ok(Some(main)) => main,
        _ => seed::body().into()
    };

    seed::App::build(init, update, view)
        .sink(update);
        .mount(mount_point)
        .routes(routes)
        .finish()
        .run();
}
```

**Comment by AlterionX** [comment]
Yes, definitely. I haven't gone back and looked at that code at all -- should probably fix that at some point.

On the other hand, regarding the submodules, I'm looking at it like this:

```rust
pub enum M {
    PageChange(Option<ModState> /* Holds the new model, or none if should be default or something else */),
    RouteChange(Url /*or something similar*/),
    Mod0(mod0::M)
    // -- snip: repetition
}
fn update(m: M, Store { store: global_store, location: store }: &mut Store, orders: &mut impl Orders<M, M>) {
    match msg {
        M::NoOp => (),
        M::Routing(loc) => {
            loc.prep_page_for_render(&model.loc, &model.store, orders);
            // send change page here
        },
        // -- snip (custom code for "top level" messages)
        M::Mod0(m) => {
            log(format!("Handling mod0 update {:?}.", m).as_str());
            if let ModData::Mod0(store) = &mut store { // this is since the page can hold different pieces of data. also, is it possible to  you manage to 
                mod0::update(m, s, global_store, &mut orders.proxy(M::Mod0));
            } else {
                orders.skip();
            }
        },
        // -- snip (you can use a macro to generate the rest of the branches as it's a fairly mechanical task)
    }
}
```

If you're adding a sink, then (given this update structure) it's still the same operations to me. I'm just handling the global messages together with my other messages. You can also send messages between people by sending it as a global message with the `M::ModNum` enum constructor.

A possible benefit that I can see is segregation of messages? But I can add another enum field (`M::Global(global::M)` or something) to do that.

**Comment by MartinKavik** [comment]
Let's look at the part of `seed-rs-realworld`:

a) There is `lib.rs` aka `root-module`.
b) `root module` connects `pages` aka `sub-modules` with Seed's runtime.
c) Some `sub-modules` (`home.rs`, `profile.rs`) connect `feed.rs` aka `sub-sub-module`.

Parent is always responsible only for "plumbing" - it's de facto Seed's runtime from its child view. 
It has two advantages: 
- It's easy to find out what's going on, because only parent has access to its children and children can't modify parent.
- Children doesn't need to know anything about parent, so they can be reusable (e.g. `feed.rs`).

But it has also one big disadvantage - how to notify parent / sibling / root / .. (aka. `target-module`)?
Some options:
1. I can call directly `target-module`'s `update` function - very ugly, confusing and I will probably fight with types. 
1. I can invoke `target-module`'s `update` function through `orders` with `target-module`'s `Msg` - less ugly but confusing because `target-module` doesn't know if the sender is other module or `update` was invoked because of some internal processes. We basically breaks encapsulation here - `Msg` should be sent and handled by the same module.
1. Like `2.`, but we use other, "independent" `Msg` - `GMsg` - so we don't break encapsulation. This pattern is a bit similar to `NoMap` (see https://medium.com/@_rchaves_/child-parent-communication-in-elm-outmsg-vs-translator-vs-nomap-patterns-f51b2a25ecb1).

So that's my reasoning behind it. I've tried to make it as readable and explicit as possible, but there are other ways of course.  I took a lot of inspiration from https://github.com/rtfeldman/elm-spa-example for the first pattern (there isn't an alternative for the second one because "incoming" events/msgs are fired by Effect Managers). 

---

> A possible benefit that I can see is segregation of messages? But I can add another enum field (M::Global(global::M) or something) to do that.

Yeah, basically point 3. There is no silver bullet - use what is the best for your project. `sink` is just one tool which (I hope) makes building Seed apps easier.

> I have looked at that PR, by the way, as well as the real-world implementation. Awesome work. My own personal site took a lot of inspiration from it.

Thanks! I'll maybe add your comment to my site and don't hesitate to create PR with your site here: https://github.com/MartinKavik/awesome-seed-rs :)

**Comment by AlterionX** [comment]
Ah, I see, it makes sense now (mostly). For some reason, I'd forgotten about all the mapping that you would need to do to send a signal to an arbitrary model. So I guess `sink` is a specialization of `update` for the global case. (basically `M::Global(g_msg) => sink(g_msg)` in my case?) Thanks for the help!

Those are some good articles. I've never actually programmed in Elm before, so all of that was new knowledge to me. I do extensively use/implement messaging systems elsewhere, so it's super nice to see the different ways people use/compose/transform messages.

I was planning to submit a PR! I need to push a v1 out the door first, though.

Also, as for the `log!`, I didn't know about that. I am about to integrate the logging crate into my debug build in a moment, but this is good to know for a smaller project in the future! My hands hurt from typing all the `format!`s.

**Comment by MartinKavik** [comment]
> So I guess sink is a specialization of update for the global case and effectively canonicalizes it?

Yeah, I think this is the best definition.

> I've never actually programmed in Elm before

I've written only several thousand lines in Elm in pet projects but it was enough to change my programming style. When I'm trying to resolve / design something in Seed, I look first at the Elm world. And when I'm writing backend in Actix, I'm looking at Elixir world.

> Also, as for the log!, I didn't know about that.

Yeah, we plan to make docs better.

**Comment by MartinKavik** [comment]
@AlterionX Do you have any other questions? Or do you see any problems with the API or docs? Otherwise I think we can close it.
