### ISSUE TITLE
Qeustion: Best practice for i18n?

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#287]
Does anyone built a seed app with i18n support?
If so, would you mind to share your experiences?

**Comment by MartinKavik** [comment]
Unfortunately I'm building only English apps. But there are some interesting projects which can help a little bit, e.g. https://projectfluent.org/.
Let me know when you encounter some problems / want to share your experience.

**Comment by AlterionX** [comment]
While I haven't implemented i18n support within Seed, I have done it elsewhere (Android, mostly). I also don't know how much you do know, so this is a bit of an infodump of everything I know about i18n.

How I have seen it implemented is with this basic concept:

Somewhere in memory, on disk, or elsewhere is a massive two way dictionary of (`Locale`, `T`) to `&str` where `T` is something that has `PartialEq` implemented (usually a string saying what the purpose of this string is). Let's call this the `i18n_map`. Then wrap EVERY user facing string that needs translating with a call to this function or some analog:
```rust
// You may want to make `l` a global variable instead of having it as a parameter, but this is usually preferred.
fn i18n(id: T, l: Locale) -> Option<String> {
    i18n_map.get((l, id)) // get the corresponding string with the locale and purpose
}
fn i18n_with_default(id: T, l: Locale, default: &str) -> &str {
    i18n(l, id).unwrap_or(default) // get the string or a default if cannot be found
}
```
You could (theoretically) do this programmatically, but that's hard since (sometimes) there's text that you don't want to translate or text that needs to be translated in parts, especially if you have custom attributes that are used for display vs layout or behavior. And of course, this approach simplifies things a little too much, but it's usually enough...

These maps are usually stored in auxiliary files at a path that's similar to `i18n/{locale}.[xml, json, blah]` with whatever format, of course. You can include these in the final binary with `include_string` or something similar.

Additionally, this map can be big, especially if it's an SPA. You may want to only send the relevant locales. This would require some code that only sends the required localization strings, usually by examining the Accept-Language HTTP header, so this is some server-side work, not client-side. I have a few ideas on how to do this, but they're mostly hacky, usually unnecessary for a small project and not directly related seed, so I'm not going to write those down here.

There's also all sorts of issues that relate to i18n implementations, but I don't think those really apply here. Some have entire DSLs created to accomplish this task. But, once again, the basic approach is usually enough...

Anyways, this functionality is usually handled in a entirely separate library since it's usually complicated enough to require this.

I then did a bit of research into i18n crates for Rust, specifically. The state of Rust's i18n overall is ok, but not stable (see [awwy](https://www.arewewebyet.org/topics/i18n/)). Unfortunately, I'm not sure that all the libraries there work in a browser. I personally also have not used any of these.

**Comment by flosse** [comment]
@AlterionX Thanks for sharing your thoughts.
Actually I started with super simple `TxtKey` and  `Lng` enums in combination with a simple lookup function ;-)
But probably I'll have a closer look at projectfluent (Thanks @MartinKavik) and other crates out there.

I'll close this issue for now.
And of course I'll share my experiences with you in the future :)
