### ISSUE TITLE
Controlled components not possible

### ISSUE THREAD

**Issue by aidanhs** [David-OConnor/seed#33]
See https://github.com/DenisKolodin/yew/issues/233#issuecomment-457886532 for context.

Essentially, the desired behavior is: if an edit for a field (e.g. an input or text area) is 'rejected' (i.e. not applied to the model), the render should not update. In react this is known as 'controlled components'.

In seed you can test this by commenting out [this line](https://github.com/David-OConnor/seed/blob/0f835d3f64ee44ba64cc7496a8504c754d9b6253/examples/todomvc/src/lib.rs#L284) from the todomvc example and then trying to edit an item. Because the internal state isn't changing, arguably neither should the render. Unfortunately, it does.

React solves this by restoring state after a change event (described on the linked issue).

**Comment by David-OConnor** [comment]
Need to think on what the best desired behavior is on this. For context, I was struggling with a related issue in React earlier this week, where I'd get nasty input lag on text inputs, and wanted a quick way to just let them take input and not update state until blur.

**Comment by aidanhs** [comment]
React does have a concept of uncontrolled components as well - https://reactjs.org/docs/uncontrolled-components.html

I personally think react's controlled component approach is intuitively better (the whole idea of render is that it means your dom is derived from your state), but the important thing is that there should be a way to do either depending on your needs.

I quite like react's way of exposing it because it's easy to opt out of - if you don't set the `value` property, it's uncontrolled (because you're not passing down the value you want to be set).

**Comment by David-OConnor** [comment]
Latest commit has a basic implementation of this. Notes:

- Set it so all components are controlled, based on notes on that React link; uncontrolled components are now no longer possible (breaking). I think this is worth it to enforce that render always matches state.
- The TodoMVC example, which I based off the official React/TS one, relied on a uncontrolled component for the main entry box; fixed.
- I suspect the approach I used is fragile: It checks if input/textarea/select els have an "input" event, and if not, add one which reverts them to their prev value.
- Does not currently keep checkboxes in sync; will implement later after thinking about the best approach. Based on prev note, not sure how to handle. (Eg need to handle cases of click, dbl/rightclick, maybe others)

**Comment by David-OConnor** [comment]
Published in v0.2.5

**Comment by tiberiusferreira** [comment]
> * I suspect the approach I used is fragile: It checks if input/textarea/select els have an "input" event, and if not, add one which reverts them to their prev value. This might be missing some use cases.

> Overall: My understanding is that the purpose of this is to keep input elements from getting out of sync with the model.

But currently it doesn't keep the model and input element in sync if they have an "input" event. I just bumped into this.

 To keep it in sync it would be necessary to have a listener checking the input value property (set by the user listener) and setting the actual value with input_el.set_value(value), right?

**Comment by tiberiusferreira** [comment]
In order to keep the "value" property set by the user in sync with the render we could get the value property and use set_value right after the user event handler.

I have it implemented here: 

https://github.com/tiberiusferreira/seed/commit/d14e778bc92fcb6327f76c1e43dba4ceed83349d

I tested on Safari, Firefox and Chrome. 

For the case when the input field was invalidated (such as when the user typed a letter on a number input) the value property is set to empty. 
When this happens I set the value as the default_value. This works because when we set the value using set_value the default_value is also set, but it doesn't get cleared when the input is invalidated.

I'm not sure if this is what you guys had in mind, or the desired behaviour. If it is, I'm happy to make a PR or you can just copy paste my changes.

**Comment by David-OConnor** [comment]
Tried it - looks nice. Fire away with that PR.

**Comment by tiberiusferreira** [comment]
Setting the value with set_value breaks inputs of type file.

 I'm working on a fix which checks the input type and only uses set_value on number, text and password.  I'm not sure if it should also be set for other input types, we might need to whitelist others later. 

Just letting you know.

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/seed/pull/54

I did some reflowing. Checkboxes are now kept in sync from clicking, but there are still some cases where items can get out of sync, such as if a Value isn't specified, or something other than text entry changes the model.

**Comment by jesskfullwood** [comment]
The current impl seems broken for `select` elements. e.g. I have
```
select![
    option!["a"],
    option!["b"],
    option!["c"],
    attrs! {At::Value => model.v},
    input_ev(Ev::Input, Msg::NewV)
],
```
I get the error: ```
panicked at 'Unable to cast as an input element', src/libcore/option.rs:1038:5
```
This appears to be because the `event.target()` is a being to downcast as an `HtmlInputElement` but actually it is an `HtmlSelectElement` - [see here](https://github.com/David-OConnor/seed/blob/c69e9b8efb67ba2e7103b1e973f80a42c9729392/src/dom_types.rs#L210).

**Comment by David-OConnor** [comment]
Fixed with a bandaid to mattern match on casting instead of using the helper func. More fundamentally, I'd like to replace that chunk of logic you linked with that in attach_control, which ties more directly with the model instead of relying on defaultValue. Broken atm. I think this bandaid doesn't enforce sync for select.

Is it normal to use select elements without values on the option? Does the text control (Eg "a" for your ex) replace the option?

**Comment by David-OConnor** [comment]
`select` works in latest release. Leaving this open since may change some implementation details, and `select`s aren't controlled. 

Considering some type of shim to prevent app slowdowns from interfering with typing.
