### ISSUE TITLE
Hooking into lifecycle events for cleanup

### ISSUE THREAD

**Issue by johnsonw** [David-OConnor/seed#82]
## Description

Components have lifecycle hooks but do not provide a means to update the state of the app. This makes it difficult to cleanup any component actions. For example, consider a component that when mouseover occurs, will fetch data every ten seconds. When I leave the page and the component unmounts, I can catch the unmount event, but I have no way to send a message that would allow me to stop fetching. 

I was able to handle this before the update to 0.3 by using `state.update` in the view function; but state is no longer passed in as an argument. At the moment, we are slowly integrating seed into an existing app, so we are not at the point where we are using routes (I think I could hook into there if I was). I think the easiest thing (from my point of view) would be to provide a way to send messages in lifecycle callbacks, similar to how events can send messages in their callback function. Is this something that can be done?

Regards,

Will

**Comment by David-OConnor** [comment]
The API I'm thinking for this is a `seed::update` function that can be called anywhere. Need to sort out the implementation.

**Comment by David-OConnor** [comment]
It might be more feasible to implement having the lifecycle hooks return an Option<Msg> that can be used to update state once complete with side-effects.

**Comment by David-OConnor** [comment]
WIP API: `did_mount(|_| log!("mounted")).update(Msg::DoThis)`

**Comment by David-OConnor** [comment]
Added my progress to latest commit (Breaks tests, but not code). Panics if you attempt to use the `.update2()` syntax described above.

**Comment by David-OConnor** [comment]
Note: Tests are currently broken due to this WIP change. Expect them to be broken until resolved.

**Comment by johnsonw** [comment]
Thanks @David-OConnor, will take a look at this when I get a chance.

**Comment by David-OConnor** [comment]
@MartinKavik fixed the tests, and the PR he referenced above will likely to the solution to this issue.

**Comment by anlumo** [comment]
`update2()` doesn't do anything for me, it's not sending any messages.

Anyways, this API does not provide a way to pass the node passed to the lifecycle closure to the event. I'm trying to integrate a canvas element into seed, which needs both the model and the `HtmlCanvasElement` (aka `Node`) at the same time. Seed provides a `canvas!` macro, but I don't think it can actually be used at this point.

**Comment by David-OConnor** [comment]
Didn't get update2 (WIP name) working yet. Still need to fix.

**Comment by zimond** [comment]
Any progress here?

**Comment by David-OConnor** [comment]
Nope

**Comment by jgrund** [comment]
Is this able to be handled by `seed::update`?

**Comment by jgrund** [comment]
Is there a way to do this in 0.4.0? Looks like the `update2` fn has been removed.

Would it be possible to have the lifecycle hooks return a message?

**Comment by MartinKavik** [comment]
@jgrund Could you provide an example(s) so we/I can help you resolve your issues and it's clear what are you trying to do? 

Note: In 0.4.0 you can get `App` instance to call `app.update(..)` from `orders`. 
Example: https://github.com/David-OConnor/seed/blob/master/examples/animation_frame/src/lib.rs#L72

**Comment by jgrund** [comment]
@MartinKavik Sure, in my case I'm trying to propagate the validation state of an `input` to the model when `did_mount` fires. There doesn't appear to be an easy way to do this within the view.

**Comment by MartinKavik** [comment]
I haven't used hooks before so I've created a simple example from the quick source code exploration: https://github.com/MartinKavik/seed/blob/demo/did_mount/examples/did_mount/src/lib.rs.
But it doesn't work and API seems a little bit weird on the first glance.

So I suggest to :
1. Create a new issue dedicated to general hook APIs.
1. Find out current state of hooks.
1. Prepare some real-world examples because hooks can be easily abused to do VirtualDOM's work by reading and modifying DOM and it's hard to debug it. And we need something for integration tests.
1. Redesign API if necessary.
1. Write some unit tests and implement it.

@David-OConnor what do you think?

**Comment by David-OConnor** [comment]
I don't use hooks myself, here or elsewhere - if there are ways around them in most cases, we can ditch the hooks api entirely. Need a good understanding of what the common use-cases.

**Comment by zimond** [comment]
My use case: I use a hook into a canvas element and render the canvas when it's initialized. I think this could be quite common for html canvas-heavy apps

**Comment by MartinKavik** [comment]
I investigated it a little bit and found some related discussions in the Elm world:

1. https://github.com/elm/virtual-dom/issues/11
2. https://github.com/elm/html/issues/19

It looks that hooks are useful in some special cases but Elm still doesn't support them because we don't need them in the most cases and it can be hard to design it properly.

---

Back to specific use-cases:
1. @zimond's one - Canvas element
    - There is [Elm library](https://github.com/joakin/elm-canvas) which uses custom element (see [elm-canvas.js](https://github.com/joakin/elm-canvas/blob/master/elm-canvas/elm-canvas.js) and [element creation](https://github.com/joakin/elm-canvas/blob/master/src/Canvas.elm#L122)). So we can use custom elements for cases like this but I don't know if it's a workaround or a proper solution.

1. @jgrund's one - Propagate validation state of an `input` to the model
   - It sounds a little bit weird to me but we probably need more context here.

1. @johnsonw's one - Stop fetching on component unmount when leaving page
   - > At the moment, we are slowly integrating seed into an existing app, so we are not at the point where we are using routes (I think I could hook into there if I was).
      - I agree with you that you should "listen" route/page changes (or some other reliable events) instead of a component unmount. (Un)mounting is async because Seed waits for the next animation frame to rerender page so It's possible that according to your `Model` you are already on the other page but it still fetches. 
So it seems like an anti-pattern to me and you can probably use some workarounds while you are integrating Seed into existing application.

**Comment by jgrund** [comment]
Some more context, I am utilizing the built-in HTML5 validation API: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Using_built-in_form_validation. 

My usecase is conceptually simple; I want to display the error message from a required attribute when the element mounts on the page. I want to do this with a custom error tooltip. Ex:

<img width="969" alt="Screen Shot 2019-08-13 at 9 02 48 AM" src="https://user-images.githubusercontent.com/458717/62949821-e7aabc80-bdb4-11e9-8829-9e6584fbaa61.png">

The tricky part is that the DOM controls essentially own that error message (accessible via https://docs.rs/web-sys/0.3.25/web_sys/struct.HtmlInputElement.html#method.validation_message, so I need a way to persist that message to the model when the component loads so it can be rendered into that tooltip.

If I could trigger a message when the element mounts, I could persist it through the update fn.

If there is some other way to utilize that message in the tooltip on page load (rather than hooks), I'd be happy to do that as well.

**Comment by MartinKavik** [comment]
I've created an example of custom "tooltip" with an error message. 
- https://github.com/MartinKavik/seed/blob/demo/did_mount/examples/did_mount/src/lib.rs
- You can clone branch and run `cargo make start did_mount` from the root.

---

However there is one thing which I don't understand:
>   in the tooltip on page load

@jgrund: Why on page load? - When do you run form validation?

---

P.S. There is `Ev::Invalid` in example. It's missing in Seed, it's `todo` - I'll probably create a new issue or add missing events.

**Comment by MartinKavik** [comment]
> if there are ways around them in most cases, we can ditch the hooks api entirely

I'm starting to agree with @David-OConnor. See this comment: https://github.com/David-OConnor/seed/issues/200#issuecomment-522235968. Custom elements seem to be a better alternative (also in Elm world - see https://guide.elm-lang.org/interop/custom_elements.html).

To support custom elements we probably just need to add API to support custom events (and it will be nice to add missing official events as well). I'll create an issue if we agree on this.

**Comment by MartinKavik** [comment]
FYI, there is a new API and examples:

@zimond's - Canvas element 
  - see the [canvas example](https://github.com/David-OConnor/seed/blob/a3dfe6cbf4f165c195fd2b130db059094761cf04/examples/canvas/src/lib.rs#L41) :)
  - and JS [custom element](https://github.com/David-OConnor/seed/blob/a3dfe6cbf4f165c195fd2b130db059094761cf04/examples/mathjax/public/math-tex.js#L4) 
  - and Typescript [custom element](https://github.com/MartinKavik/seed-rs.org/blob/152d9a9d0a1f5075ecbd49e56baa6f378bd330a8/web_components/code-block.ts#L5)

@jgrund 
> If there is some other way to utilize that message in the tooltip on page load (rather than hooks), I'd be happy to do that as well.

I think you can use also the new API `orders.after_next_render`. See [canvas example](https://github.com/David-OConnor/seed/blob/a3dfe6cbf4f165c195fd2b130db059094761cf04/examples/canvas/src/lib.rs#L24).

---

I think we can close the issue.

**Comment by johnsonw** [comment]
@MartinKavik Thank you for the updates. I'll close the issue.
