### ISSUE TITLE
Recommended way of triggering model events from outside of normal flow.

### ISSUE THREAD

**Issue by thedodd** [David-OConnor/seed#85]
To explain this a bit better, I need to be able to trigger a model update event from a closure passed to JS land. Take the websockets example for reference. Currently, it is recommended to pass a clone of the `App<_, _>` to the various callbacks so that they can push updates to the system as needed. 

However, this is complicated when the websocket goes down and a new one needs to be established. In such a case, we would need to have a reference to the `App<_, _>` somewhere in the model so that it can be accessed when a new Websocket needs to be built, which will require new callbacks to be attached to the new Ws.

Seems like we could accomplish this by emitting an event to the model which takes a clone of the app, which would then be stored somewhere on the model for later use. This creates a cycle ... and definitely feels dirty ... but is a path forward. Especially because the cycle doesn't matter due to the fact that the app will most likely be alive for the entire duration of the program.

Thoughts?

**Comment by David-OConnor** [comment]
Elegantly handling this has been a thorn for a while. [This issue](https://github.com/David-OConnor/seed/issues/82) is tangentially related; this week, I've been trying to allow lifecycle hooks to update state through a dedicated method. Release 0.3 removed the system of passing `app` down through view funcs - an approach I never liked, and used only due to not having found a way to implement alternatives.

Am open to making breaking API changes to finally solve this. Your proposal (The implementation's not immediately coming to mind) is probably better than not having a way to handle this. The ideal API would be a `seed::update()` function that can be called anywhere, but I'm not sure how to implement this.

**Comment by MartinKavik** [comment]
See PR https://github.com/David-OConnor/seed/pull/96, pls
